<a href="https://colab.research.google.com/github/vamshi-kb/Covid19-Detection-Using-Chest-X-Ray/blob/master/Tensorflow_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
from termcolor import colored

In [ ]:
print(('Your TensorFlow version: {0}').format(tf.__version__))

Your TensorFlow version: 2.3.0


In [ ]:
import time
cpu_slot=0
gpu_slot=0

#Using CPU at slot 0
with tf.device('/CPU:'+str(cpu_slot)):
  #Starting timer
  start=time.time()

  #Doing operations on CPU
  A=tf.constant([[3,2],[5,2]])
  B=tf.constant([[3,2],[5,2]])
  print(A+B)

  end=time.time()- start
  print("using CPU", end)
  print("\n")

#Using the GPU at slot0
with tf.device('/GPU:'+str(gpu_slot)):
  #Starting timer
  start=time.time()

  #Doing operations on CPU
  A=tf.constant([[3,2],[5,2]])
  B=tf.constant([[3,2],[5,2]])
  print(A+B)

  # Printing how long it took with CPU
  end = time.time() - start
  print("using Gpu",end)

tf.Tensor(
[[ 6  4]
 [10  4]], shape=(2, 2), dtype=int32)
using CPU 0.0007894039154052734


tf.Tensor(
[[ 6  4]
 [10  4]], shape=(2, 2), dtype=int32)
using Gpu 0.0014758110046386719


TensorFlow programs use a data structure called tensor to represent all the data. Any type of data you plan to use for your model can be stored in Tensors. 
Simply put, a Tensor is a multi-dimensional array (0-D tensor: scalar, 1-D tensor: vector, 2-D tensor: matrix, and so on). 
Hence, TensorFlow is simply referring to the flow of the Tensors in the computational graph.

Tensor is multi dimensional array

A scalar is rank_0_tensor

A vector is rank_1_tensor

A matrix is rank_2_tensor

**Scalar**

In [ ]:
x=tf.constant(3.0)
print(x,x.dtype)

tf.Tensor(3.0, shape=(), dtype=float32) <dtype: 'float32'>


Vector

In [ ]:
x=tf.constant([3,5,7])
print(x)

tf.Tensor([3 5 7], shape=(3,), dtype=int32)


Matrix

In [ ]:
x=tf.constant([[3,5,7],[3,5,7]])
print(x)

tf.Tensor(
[[3 5 7]
 [3 5 7]], shape=(2, 3), dtype=int32)


Tensor

In [ ]:
x=tf.constant([[3,5,7],[3,5,7],[3,5,7]])
print(x)

tf.Tensor(
[[3 5 7]
 [3 5 7]
 [3 5 7]], shape=(3, 3), dtype=int32)


Stacking

In [ ]:
a=tf.constant(3)
print(a)

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
b=tf.stack([a,a])
print(b)

tf.Tensor([3 3], shape=(2,), dtype=int32)


In [ ]:
c=tf.stack([b,b])
print(c)

tf.Tensor(
[[3 3]
 [3 3]], shape=(2, 2), dtype=int32)


Slicing

In [ ]:
a=tf.constant([[1,2,3],[4,5,6]])
# print(a)

sliced_a=a[:,1]
print(sliced_a)

tf.Tensor([2 5], shape=(2,), dtype=int32)


In [ ]:
sliced_b=a[0,:]
print(sliced_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


Reshaping

In [ ]:
reshaped_a=tf.reshape(a,[3,2])
print(reshaped_a)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


Variable

In [ ]:
var=tf.Variable([2,3],dtype=tf.int32,name='Var')
print(var)

<tf.Variable 'Var:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>


In [ ]:
print("Shape:",var.shape)
print("Dtype:",var.dtype)
print("As Numpy",var.numpy)

Shape: (2,)
Dtype: <dtype: 'int32'>
As Numpy <bound method BaseResourceVariable.numpy of <tf.Variable 'Var:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>>


In [ ]:
var_add=var.assign_add([3,4])
print(var_add)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([5, 7], dtype=int32)>


In [ ]:
var_sub=var_add.assign_sub([1,1])
print(var_sub)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


Operations

In [ ]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

b= tf.constant([[1, 2],
                 [3, 4]])

print(b)

print(colored("Addition\n","blue"),a+b)# all other operations
print(colored("element wise multiplication\n", "blue"),a*b) # element-wise multiplication
print(colored("matrix multiplication\n", "blue"),a @b ) # matrix multiplication

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Addition
 tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)
element wise multiplication
 tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
matrix multiplication
 tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)


Other useful Operations

In [ ]:
c = tf.constant([[1.0, 2.0],
                 [3.0, 5.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor([1 1], shape=(2,), dtype=int64)
tf.Tensor(
[[0.26894143 0.7310586 ]
 [0.11920291 0.880797  ]], shape=(2, 2), dtype=float32)


Zeros

In [ ]:
tf.zeros(shape=[3, 3], dtype=tf.int32)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

Ones

In [ ]:
tf.ones(shape=[3,3],dtype=tf.float32)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

Cast types

In [ ]:
tensor = tf.constant([[3.1, 2.8],
                      [5.2, 2.3],
                      [9.7, 5.5],
                      [1.1, 3.4]], 
                      dtype=tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)
print(tensor_as_int)

tf.Tensor(
[[3 2]
 [5 2]
 [9 5]
 [1 3]], shape=(4, 2), dtype=int32)


Function

In [ ]:

# Define a Python function
def function_to_get_faster(x, y, b):
  x = tf.matmul(x, y)
  x = x + b
  return x

# Create a `Function` object that contains a graph
a_function_that_uses_a_graph = tf.function(function_to_get_faster)

# Make some tensors
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

# It just works!
a_function_that_uses_a_graph(x1, y1, b1)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>

In [ ]:
print(x1)

tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)


In [ ]:
print(y1)

tf.Tensor(
[[2.]
 [3.]], shape=(2, 1), dtype=float32)


In [ ]:
print(b1)

tf.Tensor(4.0, shape=(), dtype=float32)


Graph

Graphs are data structures that contain a set of tf.Operation objects, which represent units of computation; and tf.Tensor objects, which represent the units of data that flow between operations.

The way you create a graph in TensorFlow is to use tf.function, either as a direct call or as a decorator.

In [ ]:
# Don't read the output too carefully.
print(tf.autograph.to_code(function_to_get_faster))

def tf__function_to_get_faster(x, y, b):
    with ag__.FunctionScope('function_to_get_faster', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        x = ag__.converted_call(ag__.ld(tf).matmul, (ag__.ld(x), ag__.ld(y)), None, fscope)
        x = (ag__.ld(x) + ag__.ld(b))
        try:
            do_return = True
            retval_ = ag__.ld(x)
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



Feed Forward

In [ ]:
n_input=4
n_hidden1=3
n_hidden2=3
n_output=2

weights = {
    'w1': tf.Variable(tf.random.truncated_normal([n_input, n_hidden1], stddev=0.1)),
    'w2': tf.Variable(tf.random.truncated_normal([n_hidden1, n_hidden2], stddev=0.1)),
    'out': tf.Variable(tf.random.truncated_normal([n_hidden2, n_output], stddev=0.1)),
}
biases = {
    'b1': tf.Variable(tf.constant(0.1, shape=[n_hidden1])),
    'b2': tf.Variable(tf.constant(0.1, shape=[n_hidden2])),
    'out': tf.Variable(tf.constant(0.1, shape=[n_output]))
}

In [ ]:
weights['w1'].shape

TensorShape([4, 3])

In [ ]:
weights['w2'].shape

TensorShape([3, 3])

In [ ]:
biases['out'].shape

TensorShape([2])

In [ ]:
weights['out'].shape

TensorShape([3, 2])

In [ ]:
x=tf.Variable([[1.0, 2.0, 3.0,4.0], [4.0, 5.0, 6.0,7.0],[7.0,8.0,9.0,10.0]])
output=tf.Variable([[1.0, 2.0], [4.0, 5.0],[6.0,5.0]])

In [ ]:
output.shape

TensorShape([3, 2])

In [ ]:
hidden_1 = tf.nn.sigmoid(tf.add(tf.matmul(x, weights['w1']),biases['b1']))  # hidden value calc
hidden_2 = tf.nn.sigmoid(tf.add(tf.matmul(hidden_1, weights['w2']),biases['b2']))
y_hat = tf.tanh(tf.add(tf.matmul(hidden_2,weights['out']),biases['out'])) 

In [ ]:
y_hat

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.0531711 , 0.19447406],
       [0.05346747, 0.19387846],
       [0.05361878, 0.19356258]], dtype=float32)>

In [ ]:
cce = tf.keras.losses.CategoricalCrossentropy()

In [ ]:
cce(y_hat, output).numpy()

0.15990017

In [ ]:
mse = tf.keras.losses.MeanSquaredError(reduction=tf.keras.losses.Reduction.SUM)

In [ ]:
mse(output, y_hat).numpy()

50.64581

In [ ]:
tf.nn.sigmoid((1*0.3) + (1*0.4) +(0*0.5) +(0*0.5)+0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=0.76852477>

In [ ]:
output=tf.Variable([[1.0,0.0]])

In [ ]:
y_hat=tf.Variable([[0.8037,0.1097]])

In [ ]:
mse = tf.keras.losses.MeanSquaredError()
mse(output, y_hat).numpy()

0.025283895